{
 "title": "Colliding Empires Server",
 "description": "Monitoring the Game Server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of clients",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "connected_clients", "legendFormat": "number of connected clients" }
   ]
  },
  {
   "title": "Number of lobbies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "number_of_lobbies", "legendFormat": "lobby count" }
   ]
  },
  {
   "title": "Connection Requests Since Server Start",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "connection_requests_total", "legendFormat": "total connection requests" }
   ]
  },
  {
   "title": "Number of finished games",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "number_of_finishedGames", "legendFormat": "rate of finished games" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_latency_sum", "legendFormat": "request-latencies" },
    {
     "expr": "rate(request_latency_count[1m])",
     "legendFormat": "rate-latencies"
    }
   ]
  },
  {
   "title": "Size of Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(requests_size_bytes_count[1m])",
     "legendFormat": "size of received bytes"
    }
   ]
  },
  {
   "title": "Connected Clients over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}